[default_metadata.content]
# you can add any default metadata you want here
title = "Untitled"
taxon = ""
date = "2025-12-15 00:27"
author = "Github@mujiu555"
sidebar = "true"
show-metadata = "true"
[default_metadata.options]
heading_numbering = "Bullet" # Bullet | Roman | Alphabet | None
[default_metadata.graph]
parent = "" # the default parent page

[typst_lib]
# where the typst library is located, those typst files won't be compiled to html
# but will be available for import in the typst files
# if ends with `/`, it's considerred as a directory
paths = ["lib/"]

[code_fallback_style]
dark = "#d3c6aa"
light = "#5c6a72"
